package com.carl.apollo.modal;

import java.math.BigDecimal;
import java.util.Date;

public class TFisResvProdInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.assets_no
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private String assetsNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.bg_asset_id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Long bgAssetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.product_name
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.trans_begin_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Date transBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.trans_end_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Date transEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.offline_pay_end_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Date offlinePayEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.inception_date
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Date inceptionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.due_date
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Date dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.product_limit
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Integer productLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.min_buy_amt
     *
     * @mbggenerated Sat Sep 07 14:17:25 CST 2019
     */
    private BigDecimal minBuyAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.status
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.product_rank
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Integer productRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.white_list_type
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Integer whiteListType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.white_list_group_id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Integer whiteListGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.agreement_type
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Integer agreementType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.agreement_no
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private String agreementNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.agreement_template_id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private String agreementTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.assignment_group_status
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Integer assignmentGroupStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.contract_mould_audit_status
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Integer contractMouldAuditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.contract_mould_path
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private String contractMouldPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.contract_mould_audit_remarks
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private String contractMouldAuditRemarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.product_profit_json
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private String productProfitJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.create_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fis_resv_prod_info.modify_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.id
     *
     * @return the value of t_fis_resv_prod_info.id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.id
     *
     * @param id the value for t_fis_resv_prod_info.id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.assets_no
     *
     * @return the value of t_fis_resv_prod_info.assets_no
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public String getAssetsNo() {
        return assetsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.assets_no
     *
     * @param assetsNo the value for t_fis_resv_prod_info.assets_no
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setAssetsNo(String assetsNo) {
        this.assetsNo = assetsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.bg_asset_id
     *
     * @return the value of t_fis_resv_prod_info.bg_asset_id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Long getBgAssetId() {
        return bgAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.bg_asset_id
     *
     * @param bgAssetId the value for t_fis_resv_prod_info.bg_asset_id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setBgAssetId(Long bgAssetId) {
        this.bgAssetId = bgAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.product_name
     *
     * @return the value of t_fis_resv_prod_info.product_name
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.product_name
     *
     * @param productName the value for t_fis_resv_prod_info.product_name
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.trans_begin_time
     *
     * @return the value of t_fis_resv_prod_info.trans_begin_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Date getTransBeginTime() {
        return transBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.trans_begin_time
     *
     * @param transBeginTime the value for t_fis_resv_prod_info.trans_begin_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setTransBeginTime(Date transBeginTime) {
        this.transBeginTime = transBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.trans_end_time
     *
     * @return the value of t_fis_resv_prod_info.trans_end_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Date getTransEndTime() {
        return transEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.trans_end_time
     *
     * @param transEndTime the value for t_fis_resv_prod_info.trans_end_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setTransEndTime(Date transEndTime) {
        this.transEndTime = transEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.offline_pay_end_time
     *
     * @return the value of t_fis_resv_prod_info.offline_pay_end_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Date getOfflinePayEndTime() {
        return offlinePayEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.offline_pay_end_time
     *
     * @param offlinePayEndTime the value for t_fis_resv_prod_info.offline_pay_end_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setOfflinePayEndTime(Date offlinePayEndTime) {
        this.offlinePayEndTime = offlinePayEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.inception_date
     *
     * @return the value of t_fis_resv_prod_info.inception_date
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Date getInceptionDate() {
        return inceptionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.inception_date
     *
     * @param inceptionDate the value for t_fis_resv_prod_info.inception_date
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setInceptionDate(Date inceptionDate) {
        this.inceptionDate = inceptionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.due_date
     *
     * @return the value of t_fis_resv_prod_info.due_date
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.due_date
     *
     * @param dueDate the value for t_fis_resv_prod_info.due_date
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.product_limit
     *
     * @return the value of t_fis_resv_prod_info.product_limit
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Integer getProductLimit() {
        return productLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.product_limit
     *
     * @param productLimit the value for t_fis_resv_prod_info.product_limit
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setProductLimit(Integer productLimit) {
        this.productLimit = productLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.min_buy_amt
     *
     * @return the value of t_fis_resv_prod_info.min_buy_amt
     *
     * @mbggenerated Sat Sep 07 14:17:25 CST 2019
     */
    public BigDecimal getMinBuyAmt() {
        return minBuyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.min_buy_amt
     *
     * @param minBuyAmt the value for t_fis_resv_prod_info.min_buy_amt
     *
     * @mbggenerated Sat Sep 07 14:17:25 CST 2019
     */
    public void setMinBuyAmt(BigDecimal minBuyAmt) {
        this.minBuyAmt = minBuyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.status
     *
     * @return the value of t_fis_resv_prod_info.status
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.status
     *
     * @param status the value for t_fis_resv_prod_info.status
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.product_rank
     *
     * @return the value of t_fis_resv_prod_info.product_rank
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Integer getProductRank() {
        return productRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.product_rank
     *
     * @param productRank the value for t_fis_resv_prod_info.product_rank
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setProductRank(Integer productRank) {
        this.productRank = productRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.white_list_type
     *
     * @return the value of t_fis_resv_prod_info.white_list_type
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Integer getWhiteListType() {
        return whiteListType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.white_list_type
     *
     * @param whiteListType the value for t_fis_resv_prod_info.white_list_type
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setWhiteListType(Integer whiteListType) {
        this.whiteListType = whiteListType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.white_list_group_id
     *
     * @return the value of t_fis_resv_prod_info.white_list_group_id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Integer getWhiteListGroupId() {
        return whiteListGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.white_list_group_id
     *
     * @param whiteListGroupId the value for t_fis_resv_prod_info.white_list_group_id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setWhiteListGroupId(Integer whiteListGroupId) {
        this.whiteListGroupId = whiteListGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.agreement_type
     *
     * @return the value of t_fis_resv_prod_info.agreement_type
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Integer getAgreementType() {
        return agreementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.agreement_type
     *
     * @param agreementType the value for t_fis_resv_prod_info.agreement_type
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setAgreementType(Integer agreementType) {
        this.agreementType = agreementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.agreement_no
     *
     * @return the value of t_fis_resv_prod_info.agreement_no
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public String getAgreementNo() {
        return agreementNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.agreement_no
     *
     * @param agreementNo the value for t_fis_resv_prod_info.agreement_no
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setAgreementNo(String agreementNo) {
        this.agreementNo = agreementNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.agreement_template_id
     *
     * @return the value of t_fis_resv_prod_info.agreement_template_id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public String getAgreementTemplateId() {
        return agreementTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.agreement_template_id
     *
     * @param agreementTemplateId the value for t_fis_resv_prod_info.agreement_template_id
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setAgreementTemplateId(String agreementTemplateId) {
        this.agreementTemplateId = agreementTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.assignment_group_status
     *
     * @return the value of t_fis_resv_prod_info.assignment_group_status
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Integer getAssignmentGroupStatus() {
        return assignmentGroupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.assignment_group_status
     *
     * @param assignmentGroupStatus the value for t_fis_resv_prod_info.assignment_group_status
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setAssignmentGroupStatus(Integer assignmentGroupStatus) {
        this.assignmentGroupStatus = assignmentGroupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.contract_mould_audit_status
     *
     * @return the value of t_fis_resv_prod_info.contract_mould_audit_status
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Integer getContractMouldAuditStatus() {
        return contractMouldAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.contract_mould_audit_status
     *
     * @param contractMouldAuditStatus the value for t_fis_resv_prod_info.contract_mould_audit_status
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setContractMouldAuditStatus(Integer contractMouldAuditStatus) {
        this.contractMouldAuditStatus = contractMouldAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.contract_mould_path
     *
     * @return the value of t_fis_resv_prod_info.contract_mould_path
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public String getContractMouldPath() {
        return contractMouldPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.contract_mould_path
     *
     * @param contractMouldPath the value for t_fis_resv_prod_info.contract_mould_path
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setContractMouldPath(String contractMouldPath) {
        this.contractMouldPath = contractMouldPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.contract_mould_audit_remarks
     *
     * @return the value of t_fis_resv_prod_info.contract_mould_audit_remarks
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public String getContractMouldAuditRemarks() {
        return contractMouldAuditRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.contract_mould_audit_remarks
     *
     * @param contractMouldAuditRemarks the value for t_fis_resv_prod_info.contract_mould_audit_remarks
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setContractMouldAuditRemarks(String contractMouldAuditRemarks) {
        this.contractMouldAuditRemarks = contractMouldAuditRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.product_profit_json
     *
     * @return the value of t_fis_resv_prod_info.product_profit_json
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public String getProductProfitJson() {
        return productProfitJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.product_profit_json
     *
     * @param productProfitJson the value for t_fis_resv_prod_info.product_profit_json
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setProductProfitJson(String productProfitJson) {
        this.productProfitJson = productProfitJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.create_time
     *
     * @return the value of t_fis_resv_prod_info.create_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.create_time
     *
     * @param createTime the value for t_fis_resv_prod_info.create_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fis_resv_prod_info.modify_time
     *
     * @return the value of t_fis_resv_prod_info.modify_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fis_resv_prod_info.modify_time
     *
     * @param modifyTime the value for t_fis_resv_prod_info.modify_time
     *
     * @mbggenerated Mon Jun 03 20:31:01 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}